### ISSUE TITLE
getitem method for User objects

### ISSUE THREAD

**Issue by taninamdar** [leandrotoledo/python-telegram-bot#10]
message.from_user returns a User object, which has username, first name, last name and ID fields. However, these can't be accessed by ob["username"] because there is no getitem method for User class.

**Comment by leandrotoledo** [comment]
Hi Tanmay, thank you for reporting this issue.
As you stated above, from_user is an User object, so you can access its attrs as well:

> `message.from_user.username`

Although I'll keep this open, we'll need a base  class to simplify the code so `__getitem__` could be implemented and all the Telegrams objects will inherit something like this:

> `def __getitem__(self, item):`
>     `return self.__dict__[item]`

**Comment by JASON0916** [comment]
Can we just use **ABCMeta** to make a base class?
`from abc import ABCMeta, abstractmethod`


`class Base(object):`
    `__metaclass__ = ABCMeta`

    
    def __init__(self):
        pass

    def __str__(self):
        return self.to_json()
        
    def __getitem__(self, item):
        # default result is None
        return self.__dict__.get(item, None)

    @staticmethod
    def de_json(data):
        pass

    @abstractmethod
    def to_json(self):
        pass

**Comment by leandrotoledo** [comment]
@JASON0916 yep, looks good.
1. Instead `pass` I'd use raise `NotImplementedError`.
2. Don't return None if doesn't exist, we want a KeyError, if, for instance,  user['email'].

**Comment by leandrotoledo** [comment]
I'm creating branch __testing__ so feel free to send a pull request there if you want to.

**Comment by JASON0916** [comment]
Ok, i will try 0 -0

**Comment by JASON0916** [comment]
I found two problem when i try to raise NotImplementedError in de_json and to_json.
1. NotImplementedError seems to be only effective on methods with parameter **self**, so maybe we can keep '@staticmethod' and 'pass' as before?
2. Method with @abstractmethod must be implemented by subclass, or it will raise a TypeError, just like:
TypeError: Can't instantiate abstract class XXX with abstract methods OOO
So there seems to be no need to raise a NotImplementedError?

**Comment by leandrotoledo** [comment]
All tests have passed, I've just sent ae0283f98d2e417631b4e27fb4ee5a59190068ad to fix one import error. Thanks @JASON0916

**Comment by JASON0916** [comment]
Thank you for test！^_^
