### ISSUE TITLE
Error in testing credentials, would you please guide me

### ISSUE THREAD

**Issue by Armin7Taheri** [leandrotoledo/python-telegram-bot#100]
Hello everyone and dear Leandro, thanks a lot for your awesome project.
I'm almost newbie to python, i have this issue when i wanna test if credentials are successful or not:

>>> print bot.getMe()
SyntaxError: invalid syntax

(it refers exactly to bot; it seems it has not collected completely)

....
First, i had this problem (attached "1.png" ) when i wanted to install the package on my windows, so i tried to install it manually. 
![01](https://cloud.githubusercontent.com/assets/15814185/11168238/44dbb0c6-8b9b-11e5-9603-530f8756b1ca.PNG)
I downloaded compressed file from the pypi.python.com and extract it exactly in site-packages path; but i had this error which is attached in "2.png"
![02](https://cloud.githubusercontent.com/assets/15814185/11168236/4400b19c-8b9b-11e5-98bc-e2dd9736858e.PNG)
Finally, i ran this command and i had the result that the requirement is already satisfied; So, i thought all the requirements have been installed !
![03](https://cloud.githubusercontent.com/assets/15814185/11168237/442d7970-8b9b-11e5-96e0-ab10c23d76cd.PNG)

Thanks again

**Comment by jh0ker** [comment]
Hey, would you try updating pip first? `pip install --upgrade pip` 
You're one major version behind, that might be the source of those problems.

**Comment by Armin7Taheri** [comment]
Hi dear Jh0ker :)
I'm using python 3.4
But as you said i ran upgrade command, and the result was:
requirement already up-to-date. pip in c:\python34\lib\site-packages

**Comment by leandrotoledo** [comment]
@Armin7Taheri Python 3 requires () for print, so that would mean print(bot.getMe())

**Comment by Armin7Taheri** [comment]
Yes, you're right dear Leandrotoledo. i forgot it!
Dear Jh0ker, i apologize i think i confused u, because i didn't mention it's a syntax problem at my primary issue on the Title of my question.
But i i'm going to check out whether there is any more issue or not.
