### ISSUE TITLE
Can't send_Message to myself!

### ISSUE THREAD

**Issue by veralfre** [leandrotoledo/python-telegram-bot#101]
My bots works fine with groups but when it comes to interact with a single user it does not work.
Code provided for clarification:
from twx.botapi import TelegramBot,InputFile,InputFileInfo

update_id=1
while 1
from twx.botapi import TelegramBot,InputFile,InputFileInfo

update_id=1
while 1:

    #DEBUG AGAIN:print(_updateId)
    updates=bot.get_updates(update_id+1).wait()
    #DEBUG:

    if len(updates)>0:
        #Preparo i miei vari Array e dopo di che parto con le funzioni
        update_id,message=updates[0]
        _chat=message.chat
        _chatId=_chat.id
        #Funzione di echo
        if(message.text!=None):

            #Log delle operazioni:
            """
             Message
            """
            print('Il messaggio è '+message.text+' ricevuto da +',_chatId)

            if(message.text.startswith('/echo ')):
              i=0
              while(i<5):
                bot.send_message(chat_id=_chatId,text=message.text[6:])
                i+=1

            if(message.text.startswith('/bombo')):
               """
                    Preloading BomboImg
               """
               _photoBinary=open('./bombo.jpg','rb')
               file_info=InputFileInfo('./bombo.jpg', _photoBinary, 'image/jpg')
               _inputFile= InputFile('photo' , file_info)
               bot.send_photo(_chatId,_inputFile)

**Comment by leandrotoledo** [comment]
Hi @veralfre, thanks for the bug report, but seems like you reported it to the wrong project:

from twx.botapi import TelegramBot,InputFile,InputFileInfo

It's definitely not us. Feel free to give us a try though. Let us know if you face any problem.
