### ISSUE TITLE
Not able to create instance of telegram.Bot

### ISSUE THREAD

**Issue by ravikrn** [leandrotoledo/python-telegram-bot#106]
>>>import telegram
>>>bot = telegram.Bot(token='token')
I am getting following AttributeError
AttributeError: 'module' object has no attribute 'Bot'
@leandrotoledo

**Comment by jh0ker** [comment]
@ravikrn It's a long shot, but do you have a telegram.py file in the current directory? Then it would import that, instead of the package
Else, try updating to the latest version of python-telegram-bot

**Comment by ravikrn** [comment]
['Telegram', '__builtins__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__']

**Comment by jh0ker** [comment]
Thanks. Now try this:
```
>>> from telegram import Telegram
>>> dir(Telegram)
```

Do you have another library installed, that's related to telegram?

**Comment by ravikrn** [comment]
Aaah.. I had some other package named telegram. Uninstalled it and now this package is working perfectly. Thanks a lot @jh0ker

**Comment by jh0ker** [comment]
No problem, @ravikrn :)

**Comment by mgupta2010** [comment]
@ravikrn How did you fix it? I mean how did you remove "other package telegram". I am also facing the same issue. When I run dir(telegram) command, I get following output: ['Telegram', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']. When I run dir(telegram.Telegram), I get following output: ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__']. Please someone help.

**Comment by saivisal1** [comment]
pip3 install python-telegram-bot
