### ISSUE TITLE
TelegramError: HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ravikrn** [leandrotoledo/python-telegram-bot#107]
python code:
bot.sendMessage(user_id, message, reply_markup = keyboard_message)

Error message:
"*** TelegramError: HTTP Error 403: Forbidden"

 user_id is 'int', message is 'str', keyboard_message = '{"keyboard": [["text1"], ["text2"], ["text3"], ["text4"]]}'

@jh0ker @leandrotoledo

**Comment by jh0ker** [comment]
@ravikrn You've got to send to the chat_id, not the user_id

**Comment by ravikrn** [comment]
Thanks.. My bad
