### ISSUE TITLE
Cant send Photo

### ISSUE THREAD

**Issue by matze19999** [leandrotoledo/python-telegram-bot#111]
Hey, everytime I want to send a photo, I get a a error message. Whats my failure?

https://goo.gl/photos/rSC1duRTyAsUb3iu6

**Comment by jh0ker** [comment]
You can't send photos like that. You need to upload the file with `bot.sendPhoto(chat_id=chat_id, photo=open(filename, 'rb'))` or use the file_id of an already uploaded file: `bot.sendPhoto(chat_id=chat_id, photo=file_id)`

**Comment by leandrotoledo** [comment]
Hi @matze19999, feel free to reopen if the issue persists.
