### ISSUE TITLE
webhook

### ISSUE THREAD

**Issue by Balduro** [leandrotoledo/python-telegram-bot#112]
Hi,
on the new webhook, there should be a option to create a more simple one.
Without ssl and additional path, so you can easily use it behind apache etc.

**Comment by jh0ker** [comment]
You're right, I'll make the parameters `cert` and `key` optional and modify the server settings if one or both are `None`

**Comment by jh0ker** [comment]
Thanks for the hint :) Feel free to give more suggestions here or in our telegram group :+1:
