### ISSUE TITLE
Clarification of dispatcher.py::processUpdate()

### ISSUE THREAD

**Issue by rbpasker** [leandrotoledo/python-telegram-bot#115]
Can someone clarify when a 'string update' is sent to the bot? Is this historical?

````
    def processUpdate(self, update):
....
       # string update
        if type(update) is str and update.startswith('/'):
            self.dispatchStringCommand(update)
            handled = True
        elif type(update) is str:
            self.dispatchStringRegex(update)
            handled = True
....

````

**Comment by jh0ker** [comment]
There is a function in the dispatcher called `addString[...]Handler` that allows the bot to react to updates of type `str`. Those can be inserted into the `update_queue` from elsewhere, for example from the command line. Does that answer your question? :)

**Comment by rbpasker** [comment]
yes, thank. it would be clearer if `Dispatcher` had a method `put()` with a docstring "put an arbitrary object or command on the queue to be processed by handlers via addString[....]Handler() or addTypeHandler()." I realize it is superfluous since `update_queue` is an instance variable.

**Comment by jh0ker** [comment]
Maybe we should add a `put()` method anyways, if just for clarification purposes.
