### ISSUE TITLE
Cannot import name Updater

### ISSUE THREAD

**Issue by nalex007** [leandrotoledo/python-telegram-bot#117]
Trying to:

> from telegram import Updater

but is says:

>ImportErorr: cannot import name Updater. 

What should I do?

**Comment by jh0ker** [comment]
@nalex007 This is fairly new, so it's not pushed to pypi already. Try downloading the newest version from github, if you didn't already

**Comment by nalex007** [comment]
Thank you, that worked!

**Comment by jh0ker** [comment]
We just pushed the newest version to PyPI. Happy coding!
