### ISSUE TITLE
ImportError: cannot import name 'Updater'

### ISSUE THREAD

**Issue by safir187** [leandrotoledo/python-telegram-bot#118]
I just did a clean install but there is no module named Updater. is the read me out of date?

**Comment by jh0ker** [comment]
@safir187 This is fairly new, so it's not pushed to pypi already. Try downloading the newest version from github.

**Comment by safir187** [comment]
Thanks

**Comment by jh0ker** [comment]
We just pushed the newest version to PyPI. Happy coding!
