### ISSUE TITLE
Printing an update isn't too pretty

### ISSUE THREAD

**Issue by FichteFoll** [leandrotoledo/python-telegram-bot#12]
Due to the top-down `.to_json()` approach, all the double quotes get applied and escaped recursively. Example result of calling `str(update)`, where update is for example `bot.getUpdates()[0]`.

```json
{"message": "{\"from\": \"{\\\"id\\\": 1234567890, \\\"first_name\\\": \\\"Somebody\\\", \\\"username\\\": \\\"somebody\\\"}\", \"chat\": \"{\\\"id\\\": 45858904, \\\"first_name\\\": \\\"Somebody\\\", \\\"username\\\": \\\"somebody\\\"}\", \"message_id\": 7, \"text\": \"s\", \"date\": 1437171749}", "update_id": 532670696}
```

Proposed solution: Add `datafy`, `to_data` or `to_dict` method to each data container class that is called top-down instead and define `to_json` as:
```py
def to_json(self):
    return json.dumps(self.to_data())
```

Edit: I would probably add this method in a new base class named `telegram.DataContainer` and make `to_data` abstract.

**Comment by leandrotoledo** [comment]
Thank you for your bug report, I'll be looking into this.

**Comment by leandrotoledo** [comment]
Commit 859f04e5660add9faa776f41823192e8917d7a27 has added to_data as abstractmethod on TelegramBase object. 

Thank you.
