### ISSUE TITLE
No update is recieved

### ISSUE THREAD

**Issue by psamim** [leandrotoledo/python-telegram-bot#121]
I am using the new Updater and at some point it stops polling for new updates. I used the example bot and it shows not logging info.

**Comment by jh0ker** [comment]
Hello! 

Do you see any error raised that could cause that? Did you change anything in the example bot that might have caused this? This should not happen without any errors being raised.

**Comment by jh0ker** [comment]
Would you please try getting the newest version from PyPI and try again?

**Comment by jh0ker** [comment]
Hey, if the problem persists, please reopen this issue.
