### ISSUE TITLE
Updater not available 

### ISSUE THREAD

**Issue by JulienSiems** [leandrotoledo/python-telegram-bot#122]
Just pip installed it using the instructions and the updater is not available.
Do I need to use the repo instead ?

**Comment by jh0ker** [comment]
@JulienSiems Hey, yeah the version from pypi is not the newest version. We'll push to pypi asap. In the meantime, please use to version from repo. I'll notify you when the newest version is on pypi :)

**Comment by TheCroak** [comment]
@JulienSiems If you are using pip, you can just do the following:

    pip uninstall python-telegram-bot

then:
 
     pip install git+git://github.com/leandrotoledo/python-telegram-bot/

It will update python-telegram-bot to the version on this repository

**Comment by jh0ker** [comment]
We just pushed the newest version to PyPI. Happy coding!

**Comment by JulienSiems** [comment]
great thanks for the support !
