### ISSUE TITLE
sendDocument seems to damage the file

### ISSUE THREAD

**Issue by rjdevries** [leandrotoledo/python-telegram-bot#14]
Hi Leandro,

First a Big Thanks for the great work!!! But I did find a bug.
When I use 
bot.sendDocument(chat_id=chat_id, document=open('xxx.pdf', 'r'))
It give the download, but the file is only 2kb and not readable.
I asked a other user in the telegram.Bot group and he confirmed the problem. Can you have a look at it please?

**Comment by leandrotoledo** [comment]
Thank you for your bug report, I'll be looking into this.

**Comment by leandrotoledo** [comment]
Hey there, would you mind to send me the PDF file? I couldn't reproduce the issue here.

**Comment by leandrotoledo** [comment]
Hi Ronald, could you please update to the latest version and try it again?

`pip install python-telegram-bot --upgrade`

I've tried here with the PDF you've sent me and it seems to be working:

$ md5sum uitrusting.pdf 
010b622fe01c589f5f49bb8b86777396  uitrusting.pdf
 md5sum uitrusting_downloaded.pdf 
010b622fe01c589f5f49bb8b86777396  uitrusting_downloaded.pdf

**Comment by leandrotoledo** [comment]
Windows-related issue, looking further...

**Comment by ramiro** [comment]
Aren't you supposed to use the 'b' (binary) mode `open()` flag to to open non-text files on Windows?

**Comment by franciscod** [comment]
Can someone upload the PDF for reproducing this?

**Comment by leandrotoledo** [comment]
Hi @rjdevries, would you please test it again? I've tried on Windows 7 Professional 64 bits using Python 2.7, latest release 2.4 and everything seems to be working.

**Comment by leandrotoledo** [comment]
Sample code:

    import telegram

    bot = telegram.Bot('TOKEN')

    update = bot.getUpdates()[-1]
    chat_id = update.message.chat_id
    document = open('PDF.pdf', 'rb')

    bot.sendDocument(chat_id=chat_id, document=document)

**Comment by leandrotoledo** [comment]
@rjdevries, as stated by @ramiro, you have to open() using 'b' (binary). Only 'r' will cause 1Kb file, like the issue you mentioned. I'll mark this as WAI. Thank you @ramiro, good catch.

**Comment by rjdevries** [comment]
I've tested it with the b (binary) and that works great. Thanks!
