### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by soulblader** [leandrotoledo/python-telegram-bot#20]
Hello,

Could you please add proxy support?
As a workaround, now I do smth like:

```python
import telegram
import urllib2

class Bot(telegram.Bot):
    def __init__(self, token, base_url=None, debug=False, proxy={}):
        proxy_handler = urllib2.ProxyHandler(proxy)
        opener = urllib2.build_opener(proxy_handler)
        urllib2.install_opener(opener)
        super(Bot, self).__init__(token, base_url=base_url, debug=debug)

bot = Bot(token='token', proxy=dict(http="http://host:port/"))
```

**Comment by leandrotoledo** [comment]
Hi @soulblader, does it really work for you? I thought HTTPS proxy wasn't a thing in urllib2. If I send a patch could you test?

**Comment by soulblader** [comment]
Hi there!
Yes, it does. There is a tiny notification script on nagios server. Server can't access any resource in the internet without proxy. There is http proxy.
Sure, I can check it.

**Comment by franciscod** [comment]
We can ship something like the class you posted as an example, but I'm not sure if proxy support belongs to the standard bot class

**Comment by soulblader** [comment]
Hi, @franciscod!
Oh, you're right! Proxy can be installed separately. Then, it is solved without any fixes. Thank you guys!

**Comment by franciscod** [comment]
i'd love if you sent a pull request with an example similar to what you posted here, so when someone needs a proxy has a starting point :)

**Comment by hamedRatical** [comment]
hello thank for your script but i want to create telegram bot with python 2  in addition telegram has filter in my country how i can set proxy to my bot and send message with run in cmd because i wrote scripts after that i don't have any problem bot when i run my telegrambot.py it never send an things. can you help me please i so love to create my own bot
