### ISSUE TITLE
error when trying get first_name or other data from update.message.from

### ISSUE THREAD

**Issue by proea** [leandrotoledo/python-telegram-bot#25]
error when trying get first_name or other data from update.message.from
print update['message']['from']['first_name']
File "/opt/bot/python-telegram-bot/telegram/base.py", line 17, in __getitem__
    return self.__dict__[item]
KeyError: 'from'

print update.message.from.first_name
    print update.message.from.first_name
                                            ^
SyntaxError: invalid syntax

**Comment by leandrotoledo** [comment]
from is a reserved word in Python, use from_user instead.
Em 08/08/2015 7:18 AM, "Evgenij Protasevich" <notifications@github.com>
escreveu:

**Comment by proea** [comment]
oh so) Thx!
