### ISSUE TITLE
How to get last unread message, bot.getUpdates()[-1].update_id - return last received message

### ISSUE THREAD

**Issue by proea** [leandrotoledo/python-telegram-bot#26]
How to get last unread message?

in examples:
try:
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
except IndexError:
    LAST_UPDATE_ID = None

bot.getUpdates()[-1].update_id - return last received message

This code solves the problem, but bot.getUpdates () runs 2 times
try:
    bot.getUpdates()[-len(bot.getUpdates())].update_id
except IndexError:
    LAST_UPDATE_ID = None

p.s.
in the examples have this code
try:
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
except IndexError:
    LAST_UPDATE_ID = None
...
for update in bot.getUpdates(offset=LAST_UPDATE_ID):
        if LAST_UPDATE_ID < update.update_id:
BUT LAST_UPDATE_ID the same update.update_id, if you run a bot there are new unread messages

**Comment by leandrotoledo** [comment]
Hi @proea, bot.getUpdates()[-1].update_id should return the latest item in list of updates. You can validate that looking at chat_id, the higher the newer.

This code  `if LAST_UPDATE_ID < update.update_id:` in the first time of execution will ignore the latest message gotten from getUpdates, perhaps you need to `LAST_UPDATE_ID <= update.update_id`.

**Comment by proea** [comment]
@leandrotoledo
LAST_UPDATE_ID as last unread message need for get updates:
for update in bot.getUpdates(offset=LAST_UPDATE_ID):

And LAST_UPDATE_ID <= update.update_id will not help, because in new cycle LAST_UPDATE_ID = from the last message "update.update_id" and bot.getUpdates(offset=LAST_UPDATE_ID): returned last message again. 
This solved for example replace  LAST_UPDATE_ID = update_id  by LAST_UPDATE_ID = update_id+1
