### ISSUE TITLE
Unicode compatibility issue

### ISSUE THREAD

**Issue by sooyhwang** [leandrotoledo/python-telegram-bot#27]
I found this bug while testing out my simple echo script. If I send a message in Korean, I don't get any echos back, but instead I start getting a constant stream of 500 internal server errors in the GAE log. Please see the following traceback. (Copy & paste loses all formatting, so the full traceback is in a screenshot.)

-----
File "/base/data/home/apps/s~research-bot-for-telegram/1.386316310470646493/venv/Lib/site-packages/telegram/bot.py", line 604, in _requestUrl
    urlencode(data).encode() 
File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/urllib.py", line 1307, in urlencode 
    v = quote_plus(str(v)) 
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)

-----

![2015-08-09_221616 gae unicode error traceback](https://cloud.githubusercontent.com/assets/13717847/9158549/ad6b5666-3ee6-11e5-80f0-4a0b111e2e7b.jpg)

Telegram would keep trying to resend the message (and keep failing), until I turned off echo and instead send back some generic English text.

**Comment by leandrotoledo** [comment]
Would you paste an example string?
Em 09/08/2015 11:38 PM, "S. Hwang" <notifications@github.com> escreveu:

**Comment by sooyhwang** [comment]
테스트 (test)
안녕하세요 (hello)

**Comment by leandrotoledo** [comment]
Uhm, so here is what happens, Telegram API only supports UTF-8, but Python
works with Unicode. Unicode ≠ UTF-8 and make it consistent is somehow
difficult at the moment, like the echobot.py in example folder, before
echoing back I'm encoding to UTF-8:

message = update.message.text.encode('utf-8')

This should fix the problem but I'll look further on that to make it simple
in the future.
Em 10/08/2015 12:12 AM, "S. Hwang" <notifications@github.com> escreveu:

**Comment by sooyhwang** [comment]
You're right, adding .encode('utf-8') fixed it. Thank you!

**Comment by franciscod** [comment]
Python3 has simpler unicode support :)

**Comment by leandrotoledo** [comment]
Reopening this, so we can add a method on message decorator to check if string fields are in UTF-8 prior _requestUrl. If not, try to .encode('utf-8').

**Comment by ergoz** [comment]
i think it is wrong way. Every developer should prepare their variables by themselfs, i use russian language in utf-8 and it is work without any problem, i prepare messages by myself with custom rules. Developer just need to reed few articles about unicode and utf in python. :) This is only IMHO

**Comment by leandrotoledo** [comment]
Makes sense, working as intended indeed.
