### ISSUE TITLE
Access to audio file object

### ISSUE THREAD

**Issue by Kasramvd** [leandrotoledo/python-telegram-bot#29]
As you know we can get an audio object using `message.audio` but this obj is contains a dictionary and some information about the fie,But how can I access to an audio file object? I mean its file for example save it and access to its `ogg` for mat or directly access to this file?

**Comment by leandrotoledo** [comment]
Hey, so you can't, Telegram API doesn't allow to access the file itself,
just its references.
Em 11/08/2015 4:53 AM, "kasra" <notifications@github.com> escreveu:
