### ISSUE TITLE
Force close if client send Sticker to bot

### ISSUE THREAD

**Issue by rochmad** [leandrotoledo/python-telegram-bot#30]
i have some isue if someone send sticker to my bot, thats make my bot force close 
i use python-telegram-bot/examples/echobot.py
Traceback (most recent call last):

  File "examples/echobot.py", line 271, in <module>
    echo()
  File "examples/echobot.py", line 59, in echo
    message = update.message.text.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'

thanks before

**Comment by leandrotoledo** [comment]
Hey, so, stickers are not text inside message object, I'd suggest to check
if you have text messages if you wanna to encode it:

if message.text: ...

If you want to access stickers though,

message.sticker

That's it. :)
Em 11/08/2015 8:17 AM, "Rochmad Saputra" <notifications@github.com>
escreveu:

**Comment by leandrotoledo** [comment]
Even though, I've patched the code to return an empty string instead None when a empty text message.

Thanks;
