### ISSUE TITLE
New object Voice and sendVoice method

### ISSUE THREAD

**Issue by leandrotoledo** [leandrotoledo/python-telegram-bot#39]
Seems like the API has been changed the key 'audio' to 'voice':

    1:  {
      update_id: 129566728
      message: {
        message_id: 9972
        from: {
          id: 12173560
          first_name: "Leandro"
          last_name: "S."
          username: "leandrotoledo"
        }-
      chat: {
        id: 12173560
        first_name: "Leandro"
        last_name: "S."
        username: "leandrotoledo"
      }-
      date: 1439815858
        voice: {
          duration: 0
          mime_type: "audio/ogg"
          file_id: "AwADAQADLgEAAvjAuQABIc7Q7q6ncOoC"
          file_size: 9199
        }-
      }-
    }

**Comment by JokerQyou** [comment]
Umm, there are actually two kinds of audio-related messages, `voice` and `audio`, and the corresponding methods are `sendAudio` and `sendVoice`.

**Comment by leandrotoledo** [comment]
This is probably new, I haven't seen any updates on [Bot API CHANGELOG](https://core.telegram.org/bots/api-changelog) though.

**Comment by leandrotoledo** [comment]
There we go, on sendAudio:

`Use this method to send audio files, if you want Telegram clients to display them in the music player. Your audio must be in an .mp3 format. On success, the sent Message is returned. Bots can currently send audio files of up to 50 MB in size, this limit may be changed in the future.`

`For backward compatibility, when both fields title and description are empty and mime-type of the sent file is not “audio/mpeg”, file is sent as playable voice message. In this case, your audio must be in an .ogg file encoded with OPUS. This will be removed in the future. You need to use sendVoice method instead.`

**Comment by leandrotoledo** [comment]
There is an error on [sendVoice](https://core.telegram.org/bots/api#sendvoice), instead audio it should be voice.

**Comment by leandrotoledo** [comment]
Resending an audio doesn't seem to work,

    update_id: 129566730
    message: {
      message_id: 10194
      from: {
        id: 12173560
        first_name: "Leandro"
        last_name: "S."
        username: "leandrotoledo"
      }-
      chat: {
        id: 12173560
        first_name: "Leandro"
        last_name: "S."
        username: "leandrotoledo"
      }-
      date: 1439820547
      forward_from: {
        id: 120405045
        first_name: "Toledo's Palace Bot"
        username: "ToledosPalaceBot"
      }-
      forward_date: 1439820078
      audio: {
        duration: 4
        mime_type: "audio/mpeg"
        title: "Teste"
        performer: "Leandro Toledo"
        file_id: "BQADAQADxAcAAjU8LQdOGbisOILx2QI"
        file_size: 28232
      }
    }

> bot.sendAudio(audio='BQADAQADwwcAAjU8LQdBRsl3_qD2TAI', chat_id=12173560)

      {
        ok: false
        error_code: 400
        description: "Error: Bad Request: Type of file to send mismatch"
      }

**Comment by leandrotoledo** [comment]
Looks like, even as Optional fields, to send an Audio by sendAudio using file_id you have to set the performer and title,

        message = self._bot.sendAudio(audio=str('BQADAQADwwcAAjU8LQdBRsl3_qD2TAI'),
                                      chat_id=12173560,
                                      performer='Leandro Toledo',
                                      title='Teste')

**Comment by leandrotoledo** [comment]
I'll leave this open until we get back something official from Telegram.

**Comment by leandrotoledo** [comment]
From Telegram @BotSupport:

`Hi, just becaus of backward compatibility, if we can't know, from the request, if it is an audio or a voice note, it will be sent as a voice note. This "compatibility mode" will be removed in a couple of month aprox. So for now, you shoud provide a title and/or performer in order to send the it as an audio file.`
