### ISSUE TITLE
Use bot.getUpdates() in asyncio-eventloop

### ISSUE THREAD

**Issue by yogch** [leandrotoledo/python-telegram-bot#41]
Can `bot.getUpdates()` somehow be used in an `event loop`?

**Comment by leandrotoledo** [comment]
I haven't tried yet, have you? Isn't it working? I should probably give it a try...

**Comment by yogch** [comment]
I actually new in python, so I don't really know `asyncio` :), But I know `boost::asio` so I thought it's the same :).
I actually wanted to send a question, like a discussion but I didn't find this action in `github` so I opened an issue...
I'll try it soon...

Thanks

**Comment by leandrotoledo** [comment]
@yogch Join in our Developers Group on Telegram, the link can be found on README.

**Comment by yogch** [comment]
I can't :O

**Comment by yogch** [comment]
@leandrotoledo it gave me an error message

**Comment by leandrotoledo** [comment]
Can you post it here and how to reproduce?
Thanks!
Em 21/08/2015 4:32 AM, "yogch" <notifications@github.com> escreveu:

**Comment by yogch** [comment]
Just clicking on the group in the bottom of README.rst, gives me this:
![image](https://cloud.githubusercontent.com/assets/13855845/9414333/43ca1d88-4840-11e5-8638-06ce0391b1b8.png)

**Comment by leandrotoledo** [comment]
Oops, fixed:

**Comment by leandrotoledo** [comment]
New link: https://telegram.me/joinchat/00b9c0f802509b9440b7a04db9f9eb80

**Comment by yogch** [comment]
![image](https://cloud.githubusercontent.com/assets/13855845/9425700/3a84b038-4923-11e5-9820-b7671287a707.png)

**Comment by leandrotoledo** [comment]
@yogch Ping me on leandrotoledo@ and I'll add you.

**Comment by yogch** [comment]
[python-asyncio-task-got-bad-yield] (http://stackoverflow.com/questions/30172821/python-asyncio-task-got-bad-yield)

Well, for the moment it doesn't support `asyncio` :(

**Comment by leandrotoledo** [comment]
@yogch, thanks I'll have a look.

**Comment by jh0ker** [comment]
Since we now have our own `Updater` class that runs asynchronously, we recommend using that. There are currently no plans to support `asyncio`.
