### ISSUE TITLE
sendDocument does file_content.encode()?

### ISSUE THREAD

**Issue by cosine0** [leandrotoledo/python-telegram-bot#49]
When I call `sendDocument()` with file which is already binary (`mode="rb"`), it tries to encode it once more. So if the file content is containing non-ascii byte, it faild with:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`

This is caused by here.
in **inputfile.py** line 90:
```python
    def _parse(self, form):
        if sys.version_info > (3,):
            # on Python 3 form needs to be byte encoded
            encoded_form = []
            for item in form:
                try:
                    encoded_form.append(item.encode())
                except AttributeError:
                    encoded_form.append(item)

            return b'\r\n'.join(encoded_form)
        return '\r\n'.join(form)
```

**Comment by leandrotoledo** [comment]
Uhm, would you mind to share this document so I can reproduce locallly? You can reach out me on telegram by @leandrotoledo.

Thanks for reporting this.

**Comment by cosine0** [comment]
Any file including byte>0x7f results in this error. Such as docx file, image file, non-eglinsh text

**Comment by leandrotoledo** [comment]
Found the issue?
Em 02/09/2015 9:02 AM, "cosine0" <notifications@github.com> escreveu:
