### ISSUE TITLE
New webhook support

### ISSUE THREAD

**Issue by Shevraar** [leandrotoledo/python-telegram-bot#53]
Hello!
First, thank you for your awesome library, helped me a bunch developing a simple bot!

Now to the issue: recently telegram added support for self-signed certificates to be used for webhooks
(https://core.telegram.org/bots/api#recent-changes - https://core.telegram.org/bots/api#setwebhook), would it be possible for the library to handle the transmission of the certificate whilst setting up the webhook?

Thanks!

**Comment by leandrotoledo** [comment]
Cool! Will do, thanks for the heads up.

**Comment by leandrotoledo** [comment]
Feature added on commit 05b7fda4a1a47801bf3aea0554a3bdb968c62196

**Comment by leandrotoledo** [comment]
Released on v2.8, please update using
$ pip install python-telegram-bot --upgrade

Let me know if something doesn't work, thank you for your bug report.

**Comment by Shevraar** [comment]
Will do, thank you very much!

Il giorno ven 4 set 2015 23:25 Leandro Toledo <notifications@github.com> ha
scritto:

**Comment by leandrotoledo** [comment]
If you ever wondered how to use it, here is an example:
https://gist.github.com/leandrotoledo/4e9362acdc5db33ae16c

**Comment by Shevraar** [comment]
Saw it on reddit  the other day, many thanks! I used your library in my bot
(github.com/shevraar/jovabot)

Il giorno ven 11 set 2015 02:26 Leandro Toledo <notifications@github.com>
ha scritto:
