### ISSUE TITLE
Markdown support for sendMessage

### ISSUE THREAD

**Issue by phikui** [leandrotoledo/python-telegram-bot#58]
As of September 7. telegram supports markdown messages, [see here](https://core.telegram.org/bots/api#recent-changes) and [here](https://core.telegram.org/bots/api#using-markdown)

**Comment by ergoz** [comment]
I've added this in pull request #60
waiting for aply :)

**Comment by leandrotoledo** [comment]
All tests passed. PR has been merged, thanks @ergoz 
Will bump this again once available on pip.

**Comment by leandrotoledo** [comment]
Also, implemented the new feature of JSON requests instead urlencoded data.

**Comment by leandrotoledo** [comment]
This feature has been released on v2.8.3, please don't forget to:
`pip install python-telegram-bot --upgrade`
