### ISSUE TITLE
Update_ID

### ISSUE THREAD

**Issue by hiddehoi** [leandrotoledo/python-telegram-bot#6]
Hello, could the update_id function be implemented? Otherwise i'm not able to see when to send a message?

**Comment by leandrotoledo** [comment]
Hey Hidde, all telegram.Update objects have update_id method available already.
You can simply get by update.update_id, like here:

for update in bot.getUpdates():
   print update.update_id

I've added the echobot.py example to examples folder. Check it out.
Let me know if it's working.
