### ISSUE TITLE
Problem ssl Violation Protocol

### ISSUE THREAD

**Issue by dicemans** [leandrotoledo/python-telegram-bot#64]
Hello,
i have this error ( random )

Traceback (most recent call last):
  File "keliwebBot.py", line 57, in <module>
    main()
  File "keliwebBot.py", line 28, in main
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 123, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 653, in getUpdates
    result = request.post(url, data)
  File "/usr/local/lib/python2.7/site-packages/telegram/utils/request.py", line 91, in post
    result = urlopen(request).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>

for solve i have tried to add this code in my script:

import ssl
ssl.PROTOCOL_SSLv23 = ssl.PROTOCOL_TLSv1

and not work.

**Comment by leandrotoledo** [comment]
Hi @dicemans, would you mind to share your piece of code so I can try to reproduce locally this issue?

**Comment by dicemans** [comment]
Hello,
code is your echo bot examples with my token

https://github.com/leandrotoledo/python-telegram-bot/blob/master/examples/echobot.py

only change is this:

def echo(bot):
    global LAST_UPDATE_ID
    print "leggo id: " + str(LAST_UPDATE_ID)

    # Request updates after the last updated_id
    for update in bot.getUpdates(offset=LAST_UPDATE_ID, timeout=10):
        # chat_id is required to reply any message
        chat_id = update.message.chat_id
        message = update.message.text.encode('utf-8')

        if (message == "keliweb"):
            # Reply the message
            bot.sendMessage(chat_id=chat_id, text="Find Keliweb")

            # Updates global offset to get the new updates
            LAST_UPDATE_ID = update.update_id + 1

**Comment by leandrotoledo** [comment]
Hey, thanks for the prompt reply.
It's weird though, what happens when you try to open this URL:
https://api.telegram.org/bot<TOKEN>/getMe

Does the browser show any SSL warning, etc?

**Comment by dicemans** [comment]
no any ssl warning or problem

# python
Python 2.7.9 (default, Sep 13 2015, 10:14:23) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import telegram
>>> bot = telegram.Bot(token='MYTOKEN')
>>> print bot.getMe()
{'username': u'KeliwebBot', 'first_name': u'KeliwebBot', 'id': XXXXX}

**Comment by leandrotoledo** [comment]
Is is the latest version? v2.8.3?
Can you try to run your code again? And paste the full trackback including URLError error?

Thanks!

**Comment by dicemans** [comment]
yes is last version ( 2.8.3 )

Traceback (most recent call last):
  File "keliwebBot.py", line 53, in <module>
    main()
  File "keliwebBot.py", line 30, in main
    echo(bot)
  File "keliwebBot.py", line 46, in echo
    bot.sendMessage(chat_id=chat_id, text="Trovato Keliweb")
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 123, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/telegram/bot.py", line 155, in decorator
    result = request.post(url, data)
  File "/usr/local/lib/python2.7/site-packages/telegram/utils/request.py", line 91, in post
    result = urlopen(request).read()
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:581)>

**Comment by leandrotoledo** [comment]
Ah, are you behind a proxy?

**Comment by leandrotoledo** [comment]
Try to run this:

$ openssl s_client -connect api.telegram.org:443

**Comment by dicemans** [comment]
no no any proxy or filter, i execute code in one vps.

The strange is that the code is blocked after a few cycles ( random )

# openssl s_client -connect api.telegram.org:443
CONNECTED(00000003)
depth=3 C = US, O = "The Go Daddy Group, Inc.", OU = Go Daddy Class 2 Certification Authority
verify return:1
depth=2 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", CN = Go Daddy Root Certificate Authority - G2
verify return:1
depth=1 C = US, ST = Arizona, L = Scottsdale, O = "GoDaddy.com, Inc.", OU = http://certs.godaddy.com/repository/, CN = Go Daddy Secure Certificate Authority - G2
verify return:1
depth=0 OU = Domain Control Validated, CN = api.telegram.org
verify return:1
---
Certificate chain
 0 s:/OU=Domain Control Validated/CN=api.telegram.org
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
 1 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
   i:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
 2 s:/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./CN=Go Daddy Root Certificate Authority - G2
   i:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
 3 s:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
   i:/C=US/O=The Go Daddy Group, Inc./OU=Go Daddy Class 2 Certification Authority
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIFMDCCBBigAwIBAgIIGnRjXFdR/iswDQYJKoZIhvcNAQELBQAwgbQxCzAJBgNV
BAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQHEwpTY290dHNkYWxlMRow
GAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UECxMkaHR0cDovL2NlcnRz
LmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQDEypHbyBEYWRkeSBTZWN1
cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwHhcNMTUwNTIzMTYxNzM4WhcN
MTgwNTIzMTYxNzM4WjA+MSEwHwYDVQQLExhEb21haW4gQ29udHJvbCBWYWxpZGF0
ZWQxGTAXBgNVBAMTEGFwaS50ZWxlZ3JhbS5vcmcwggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQC0oxaeXFfJiWXt6ngLropYL65ayG5JjfxXpZiIeC4LPEA8
IS6alJgzp+NCp4X60HOEARxyOTcjtVYdQ6VxFAgkpTnM3lhTlI4qQqdOLQcynrqL
0yqpnsDjzpoQlkVYesceRRQjkrtUgoiUSba+gSEAKW3Jzos5Otw1FdnrR5zvugkO
FuTZ63Iw+kmrmDF8s6wrKZGHCEFyXjXHhwQi9Uh2MG2I3/KlKRNws4cC1WtYsehz
x+TveYakB19ntHmNpCUBgozgMBfLS1z760wSUbnJBB9+0vi69TWNihw3gvAVcwBu
PRx2iwF0gT3kLKfML2bcRKgnP+rQp6jxy+raBzi9AgMBAAGjggG5MIIBtTAMBgNV
HRMBAf8EAjAAMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAOBgNVHQ8B
Af8EBAMCBaAwNgYDVR0fBC8wLTAroCmgJ4YlaHR0cDovL2NybC5nb2RhZGR5LmNv
bS9nZGlnMnMxLTg3LmNybDBTBgNVHSAETDBKMEgGC2CGSAGG/W0BBxcBMDkwNwYI
KwYBBQUHAgEWK2h0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29kYWRkeS5jb20vcmVwb3Np
dG9yeS8wdgYIKwYBBQUHAQEEajBoMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5n
b2RhZGR5LmNvbS8wQAYIKwYBBQUHMAKGNGh0dHA6Ly9jZXJ0aWZpY2F0ZXMuZ29k
YWRkeS5jb20vcmVwb3NpdG9yeS9nZGlnMi5jcnQwHwYDVR0jBBgwFoAUQMK9J47M
NIMwojPX+2yz8LQsgM4wMQYDVR0RBCowKIIQYXBpLnRlbGVncmFtLm9yZ4IUd3d3
LmFwaS50ZWxlZ3JhbS5vcmcwHQYDVR0OBBYEFAUU0MDD7w6UuyGZ56M2XCh3MJbV
MA0GCSqGSIb3DQEBCwUAA4IBAQCBk1Wv2xsue683Z4aYwact7yKekChBY72O+Ef0
X0OzeL92DfN6oV3pbPxvLouIySn9vFNgCuRQE3w1eZ5MHAIC+NgMJhcOKul6TACX
FomdiEZc3yDFbDhyUBwyQcNtZ/M7XqJDsQZBVUVD6/hg9IiDXCjkQZwU45dwgBE4
vD72+B/yJNkxeAoYbQtEFOCe6K9is3OKt5vnhE0GpZbstJYlH3+5CClJOn70nqJE
/NbkAu4AWR481D0mPxk3C0w7I4f+0VEPtwNFZuOnndjjd8LcLJCKDiCAY4yHSf+D
UH0k/30wvQCZX6lTuMf4TSs2XNGwnb4TU7gwmrPCdN5vaeD5
-----END CERTIFICATE-----
subject=/OU=Domain Control Validated/CN=api.telegram.org
issuer=/C=US/ST=Arizona/L=Scottsdale/O=GoDaddy.com, Inc./OU=http://certs.godaddy.com/repository//CN=Go Daddy Secure Certificate Authority - G2
---
No client certificate CA names sent
Server Temp Key: ECDH, prime256v1, 256 bits
---
SSL handshake has read 5433 bytes and written 375 bytes
---
New, TLSv1/SSLv3, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 92BEDE223F8078B0AB57F84B76B8D05BBBFE1388C0BF8A23173BAB2ECB5BF26D
    Session-ID-ctx: 
    Master-Key: 612FF59BE89261AEFCA4474C10378261F333D01C406F02C424FB86D288C2148F3627ACD5D4D0485872A7486F44A34069
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    TLS session ticket lifetime hint: 600 (seconds)
    TLS session ticket:
    0000 - 26 04 75 cb b2 66 13 47-6b 4a 6e 0f c6 06 cf 30   &.u..f.GkJn....0
    0010 - ac 9e 2f 7f 0c 09 06 fb-c2 05 59 25 ea a7 0d 48   ../.......Y%...H
    0020 - f0 58 be 91 da 70 78 5f-27 2e ca 88 4d 21 2a c1   .X...px_'...M!*.
    0030 - 8b d3 50 3a ba 47 18 8c-42 7e 7b ab b4 60 59 a1   ..P:.G..B~{..`Y.
    0040 - 47 5a fb de d9 29 de 2c-5d 65 60 df 11 0e 5f cc   GZ...).,]e`..._.
    0050 - 0c e3 a8 b7 a3 24 dd 70-63 e7 15 e4 5e 5b 4e a7   .....$.pc...^[N.
    0060 - 56 26 bb 74 f3 a0 b0 dc-62 12 52 99 58 3e 7b 7d   V&.t....b.R.X>{}
    0070 - b6 3f 32 61 a0 66 83 e3-bc 23 58 fd 47 7f 23 af   .?2a.f...#X.G.#.
    0080 - fa a3 95 ec 6e 72 88 f1-ff e5 12 e2 6e c8 e8 e3   ....nr......n...
    0090 - 3f b3 e2 c7 31 8a 99 e3-88 ad 11 8e be 57 a8 0a   ?...1........W..
    00a0 - 1c 7f 0f d6 b5 16 0f 5b-2b 6e 43 b8 28 82 72 86   .......[+nC.(.r.

    Start Time: 1442243882
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)

**Comment by dicemans** [comment]
Hello Leandro,
i have tested script in another server and not have any problem.

thx for support ! ;)
