### ISSUE TITLE
getting music?

### ISSUE THREAD

**Issue by incrazyboyy** [leandrotoledo/python-telegram-bot#66]
I searched the whole documentation but didnt find anything so I ask you: is it possible to download mp3 files sent to the bot? thx :)

**Comment by leandrotoledo** [comment]
Sorry, it's not as per Telegram Bot API doesn't offer any methods to download any content *yet*.

**Comment by incrazyboyy** [comment]
damn i really need that :D

**Comment by incrazyboyy** [comment]
thx anyway, I hope you'll implement it as soon as it's possible

**Comment by leandrotoledo** [comment]
No problem, as soon as Telegram team updates their API we'll certainly have it here.

**Comment by njittam** [comment]
what you can do is to have the bot resend the message to yourself and then  download the file manually.

**Comment by incrazyboyy** [comment]
Open again? Is the api update there?

**Comment by leandrotoledo** [comment]
@incrazyboyy yes, please update this library to the latest version (v2.8.4), getFile and telegram.File.download() are now methods available to download content. More info on README.
