### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by ethene** [leandrotoledo/python-telegram-bot#7]
File "py-bot.py", line 102, in <module>
    updates = bot.getUpdates(offset=current_offset, limit=100, timeout=60)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 537, in getUpdates
    return [Update.de_json(x) for x in data]
  File "/Library/Python/2.7/site-packages/telegram/update.py", line 15, in de_json
    message = Message.de_json(data['message'])
  File "/Library/Python/2.7/site-packages/telegram/message.py", line 139, in de_json
    chat=chat,
UnboundLocalError: local variable 'chat' referenced before assignment

**Comment by ethene** [comment]
Where Update is:

{u'ok': True, u'result': [{u'message': {u'date': 1436795403, u'text': u'/start', u'from': {u'first_name': u'Marina', u'last_name': u'Murlitas', u'id': 118951398}, u'message_id': 321, u'chat': {u'first_name': u'Marina', u'last_name': u'Murlitas', u'id': 118951398}}, u'update_id': 352406375}]}

**Comment by ethene** [comment]
if 'chat' in data:
            if 'username' in data['chat']:
                from telegram import User
                chat = User.de_json(data['chat'])
            if 'title' in data['chat']:
                from telegram import GroupChat
                chat = GroupChat.de_json(data['chat'])

I assume it is neither 'username' nor 'title'

**Comment by leandrotoledo** [comment]
Hey @ethene,
Thank you for your bug report.
This issue has been fixed on commit 59d55df99ed5025e2f79920a845fb1f1415857ac
Please have your lib upgraded, if on pip:

pip install python-telegram-api --upgrade

Let us know if it worked. :)
