### ISSUE TITLE
Get phone number

### ISSUE THREAD

**Issue by jtmigowski** [leandrotoledo/python-telegram-bot#75]
Dear Leandro,
I wonder how to get the user's phone number that sent a message to the bot.

**Comment by leandrotoledo** [comment]
Hi @jtmigowski,

   Currently, the API doesn't send phone number within the user data - as you can see here https://core.telegram.org/bots/api#user
    The only option would be asking the user to send a Contact (it is one of those option after attaching Video, Photo, Voice, etc on Telegram's client), more about it here https://core.telegram.org/bots/api#contact

>if message.contact:
>>print message.contact.phone_number

**Comment by jegue** [comment]
How is this now?

**Comment by rahiel** [comment]
> How is this now?

The same, but requesting a user's phone number is easier with Bot API 2.0, see the [api docs](https://core.telegram.org/bots/api#keyboardbutton) and https://github.com/python-telegram-bot/python-telegram-bot/issues/232#issuecomment-212297067. This will be supported soon in a future release.

**Comment by jh0ker** [comment]
@jegue You can use the dispatcher-rework branch of this repository, but please note that there are changes to the Dispatcher as well and the bot-api-2.0 implementation is still in beta.
