### ISSUE TITLE
video.py to_dict

### ISSUE THREAD

**Issue by ehsanskyboy** [leandrotoledo/python-telegram-bot#76]
'video':str(message.video) if hasattr(message,'video') else None,
  File "modules\telegram\base.py", line 30, in __str__
    return str(self.to_dict())
  File "modules\telegram\video.py", line 62, in to_dict
    data['thumb'] = self.thumb.to_dict()
AttributeError: 'unicode' object has no attribute 'to_dict'

**Comment by leandrotoledo** [comment]
Hi @ehsanskyboy, seems like you are using a old version of this library, please make sure you're on v2.8.7 or above.

$ pip install python-telegram-bot --upgrade

**Comment by ehsanskyboy** [comment]
i'm using 2.8.7 but get the same error when someone send a video:

'msg':msg.to_dict()
  File "modules\telegram\message.py", line 240, in to_dict
    data['video'] = self.video.to_dict()
  File "modules\telegram\video.py", line 62, in to_dict
    data['thumb'] = self.thumb.to_dict()
AttributeError: 'unicode' object has no attribute 'to_dict'

**Comment by jh0ker** [comment]
Hi! Let's try to get this sorted out :)

Please run 
`pip install python-telegram-bot --upgrade`
first, so we can confirm that this bug is still present with the latest version.

Also, please post the part where you try to send the message (The line of code where you call `bot.sendVideo(...)`)

**Comment by jh0ker** [comment]
I am unable to reproduce this bug. Do you have any more information on when this is happening?

**Comment by leandrotoledo** [comment]
Hi @ehsanskyboy, as stated by @jh0ker make sure you are using the latest version, ``pip install python-telegram-bot --upgrade``, feel free to reopen if needed.
