### ISSUE TITLE
Exception while parsing HTTPError in request.py post method

### ISSUE THREAD

**Issue by PeterZhizhin** [leandrotoledo/python-telegram-bot#79]
getUpdates method raises exception while parsing HTTPError in /utils/request.py post(url, data) method.
It goes to:
```python
    except HTTPError as error:
        if error.getcode() == 403:
            raise TelegramError('Unauthorized')
        if error.getcode() == 502:
            raise TelegramError('Bad Gateway')

        message = _parse(error.read())
        raise TelegramError(message)
```
But it seems like ```error.read()``` returns not a JSON-string so while parsing this with ```json.loads(json_data.decode())``` exception ```ValueError: Expecting value: line 1 column 1 (char 0)``` appears.

**Comment by leandrotoledo** [comment]
How often are you noticing this? Any ideas on how to reproduce?

**Comment by MakeMeASandwich** [comment]
> How often are you noticing this? Any ideas on how to reproduce?

I also experienced this.
I think the telegram servers blocked my API token for a while; I sent a lot of messages and images and had just registered the token as my first for less than a few hours.
With a second token this error message was gone and everything worked fine.
A day later the error disappeared with the first token, so it must be some kind of spam protection.

**Comment by franciscod** [comment]
We should check for `len(error.read()) == 0`

**Comment by jh0ker** [comment]
That should do the trick
