### ISSUE TITLE
echobot.py gives IndexError: list index out of range

### ISSUE THREAD

**Issue by rjdevries** [leandrotoledo/python-telegram-bot#8]
After inserting my token I did run the echobot.py

It gives me the following error

Traceback (most recent call last):
File "", line 1, in 
LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
IndexError: list index out of range

What can I try to debug this?

**Comment by leandrotoledo** [comment]
Hey @rjdevries, thanks for the issue report.
You probably don't have any update, that's why. I'll improve the error handling on this though.

Right now, you can you this snippet:

try:
    LAST_UPDATE_ID = bot.getUpdates()[-1].update_id
except IndexError:
    LAST_UPDATE_ID = 0

**Comment by rjdevries** [comment]
Yeah that's the problem. Thanks!

**Comment by leandrotoledo** [comment]
Commit 9f275371762f69713ca66007ee61671d1506f732 has added try/except block.
Thank you!
