### ISSUE TITLE
Example is hiding a no-ack issue

### ISSUE THREAD

**Issue by phalox** [leandrotoledo/python-telegram-bot#81]
Hi there,

In the examples, if you send anything but a message, your bot will keep on trying to get this update and will never increment its update counter.

https://github.com/leandrotoledo/python-telegram-bot/blob/master/examples/echobot.py#L62

Should always be execute, not just for an update. (also applies to the other example)
Thanks for the library, I like it!

**Comment by jh0ker** [comment]
Should be an easy fix by moving the `LAST_UPDATE_ID = update.update_id + 1` out of the `if`-Block

**Comment by franciscod** [comment]
+1 to @jh0ker solution

**Comment by phalox** [comment]
That's indeed the logical one.
Do you know if there are ways to do server side 'filtering' as to reduce a possible load on the bot? (slightly related to this item)
