### ISSUE TITLE
Adding a python Bot to a Group Chat

### ISSUE THREAD

**Issue by cizaquita** [leandrotoledo/python-telegram-bot#82]
There is an error adding a Bot made with this api, to a group chat. The error is on getUpdates()

**Comment by leandrotoledo** [comment]
Would you please past the full traceback?

Thanks.

**Comment by Humphreybas** [comment]
And are you sure you updated to the latest version?
```
 pip install python-telegram-bot --upgrade
```
It sounds similar to something I encountered, it was gone when I updated.

**Comment by leandrotoledo** [comment]
Ping @cizaquita :-)

**Comment by cizaquita** [comment]
Now it's okay :) thanks, i only update it and that was all

**Comment by leandrotoledo** [comment]
Cool! Thanks!
