### ISSUE TITLE
Issue with API update: 8th Oct, 2015 - message.from should be optional

### ISSUE THREAD

**Issue by hbirler** [leandrotoledo/python-telegram-bot#84]
`from` (`from_user`) property of `message` is now optional since channels do not specify which user sent a particular mesage. Currently, adding a bot to a channel causes a key error.

**Comment by leandrotoledo** [comment]
Thanks for reporting this in, I'll have a look and bump this thread again once fixed.

**Comment by franciscod** [comment]
related to #77

**Comment by leandrotoledo** [comment]
This has been released on v2.9, please run a `python-telegram-bot --upgrade`
