### ISSUE TITLE
Custom Keyboard

### ISSUE THREAD

**Issue by jtmigowski** [leandrotoledo/python-telegram-bot#93]
I created a custom keyboard with numbers and like to know how do I get the push of a button this information is not sent immediately but stored to form a string.

**Comment by jh0ker** [comment]
Hi! To cast the text of an update into a number, use `int(update.message.text)`
If you have any more questions, I'd like to invite you into our [Telegram group](https://telegram.me/joinchat/ALnA-AJQm5SEwuAzar3nvw)
