### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by maerco** [leandrotoledo/python-telegram-bot#98]
installing the module with below command

pip install python-telegram-bot

I got the error

IOError: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by jh0ker** [comment]
Hello maerco,

We'll check on that. In the meantime, you can also download the git repository and run
`# python setup.py install` 
to install the package.

**Comment by maerco** [comment]
for the moment I solved downloading the GIT

to thna run 

#pip install -r requirements.txt

**Comment by jh0ker** [comment]
Great, thank you :+1:

**Comment by maerco** [comment]
not I got an error

AttributeError: 'module' object has no attribute 'Bot'

running below script

    #!/usr/bin/env python

    import telegram
    bot = telegram.Bot('xxxxxxxxxxxxxxxxxxx')

**Comment by jh0ker** [comment]
@maerco Which version of python are you using?

**Comment by maerco** [comment]
python 2.6.5

**Comment by jh0ker** [comment]
@maerco It's a long shot, but do you have a telegram.py file in the current directory? Then it would import that, instead of the package

**Comment by maerco** [comment]
Yes... my test script it self was called telegram.py...  :+1: 

Thanks you very much, now it's work

**Comment by jh0ker** [comment]
@maerco great :)

**Comment by jh0ker** [comment]
your initial pip error should now be fixed in v2.9.2 :)
